### ISSUE TITLE
Duplicate Airplay Streams

### ISSUE THREAD

**Issue by ukypayne** [afaden/babelpod#14]
Just installed this for the first time. It is listing the same AirPlay devices 3 or 4 times. Quick testing and it seems that none of them work (most AppleTV devices). It also isn’t showing my HomePod, but I have not tried rebooting everything yet.

I do have a separate IoT vlan setup that I have passing traffic into my regular vlan with firewall settings. This may have something to do with it, but do not have the chance to reconfig my entire network structure just to test that theory and break dozens of other devices.

**Comment by masi0** [comment]
ditto - so far I have no HomePod yet testing with AppleTV. It is seem as 4-8 AirPlay: Livingroom devices under output. 

My setup is within same VLAN thus your suspicion may not be right

**Comment by zorwald** [comment]
Though this is now quite old, I can say: Using [this approach](https://github.com/afaden/babelpod/issues/17#issuecomment-657125973) by @pillar-man worked for me. I had the same problem as you, but now it works!
