### ISSUE TITLE
Playback stopping after about 3 minutes

### ISSUE THREAD

**Issue by alexfry** [afaden/babelpod#2]
Hey, great work so far.

I've got it going on a Pi3 with a Behringer UFO202 USB Phono stage + ADC.

Unfortunately something is causing playback to consistently stop after about 3 minutes.
"airplay status: stopped"

I suspect the issue might be with the underlying node_airtunes system, as I get a similar drop out when using the play_ffmpeg.js example script from them.

**Comment by alexfry** [comment]
Slight update, this seems to only really effect HomePod playback.

I'm able to stream to an older Yamaha RXA720 Receiver and have it be pretty stable.

I get no success with my AppleTV 4th gen, never seems to get a ready response.

**Comment by afaden** [comment]
Hi Alex, finally getting back to this project after a while. I've seen these dropouts in my testing as well, so I used tcpdump to see what was going on and found that the HomePod itself was terminating the connection (it was sending a TCP FIN packet). So I looked for a way to tell the HomePod to keep the connection alive, and found that setting the Airplay volume every 60 seconds or so seems to work. If you get a chance to try out the new version, please let me know if it works for you too.

**Comment by m-ruhl** [comment]
Hi @afaden 
If I set the volume on the Homepod on for example 20%, this fix resets the volume every minute to 50%.
Can you request the current volume before setting it again?

Thanks
Michael

**Comment by DjElectricUA** [comment]
In last Raspbian Os has one big problem, the Last version broke devices (2-3B+ maybe more) 
for resolving this issue I found this solution. 

sudo rpi-update e1050e94821a70b2e4c72b318d6c6c968552e9a2
---
sudo reboot
