### ISSUE TITLE
using RPi as streaming device

### ISSUE THREAD

**Issue by vespino** [afaden/babelpod#4]
Is it possible to use a RPi without the USB soundcard since I'm not interested in "line in" and use the RPi as input device instead of using a phone?

**Comment by afaden** [comment]
Finally getting back to this project after a while. I looked into your question, and found that it can be done! I [updated the blog post](http://faden.me/2018/03/18/babelpod.html#piping-system-audio-to-airplay-updated-september-3rd-2018) to explain how. Let me know if it works for you!
